nginx_conf_dir: "/etc/nginx"

worker_processes: "auto"
worker_connections: 2048
nginx_server_name: "localhost"
nginx_service_name: "nginx"
nginx_user: "nginx"
nginx_group: "nginx"
nginx_pid_file: "/var/run/nginx.pid"
nginx_worker_rlimit_nofile: 4096
nginx_error_log_level: "error"
nginx_gzip: "on"
nginx_start_service: true
nginx_start_at_boot: true
keepalive_timeout: 65
types_hash_max_size: 2048
gzip_types: "text/plain application/javascript application/x-javascript text/javascript text/xml text/css"
server_tokens: "server_tokens off"
server_names_hash_bucket_size: "server_names_hash_bucket_size 64"
log_format_name: nginx_custom
send_timeout: 600
client_body_timeout: 600
client_header_timeout: 600
proxy_send_timeout: 600
proxy_read_timeout: 600

client_max_body_size: 50M
cache: "jpg|jpeg|gif|css|png|js|ico"

server_unix: //{{ app_path_project }}/shared/tmp/sockets/puma.sock
path_root: "{{ app_path_project }}/current/public"

root: "{{ wp_source_path }}"
php_fastcgi_pass: 127.0.0.1:9000
