- hosts: tag_Role_bastion

  remote_user: "{{ ansible_ssh_user }}"
  become_method: sudo
  gather_facts: yes

  roles:
    - base
    - ssh-users
    - aws-cli
    - disable-auto-upgrade
    - hostname
    - patch-security
    - distribute-key
    - logrotate
    - fluentd-agent
    - cloudwatch-log
    - cloudwatch-metric
