# Install nodejs & npm from PPA
- name: NPM-PPA > Get script
  get_url: 
    url: "https://deb.nodesource.com/setup_{{ nodejs_setup_version }}.x"
    dest: "/home/{{ deploy_user }}/nodesource_setup.sh"
  become_user: "{{ deploy_user }}"
  become: yes

- name: NPM-PPA > Run script
  shell: bash /home/{{ deploy_user }}/nodesource_setup.sh
  become: yes

- name: NPM-PPA > Install nodejs
  apt:
    name: nodejs
    update_cache: yes
  become: yes

- name: NPM-PPA > Check nodejs version
  shell: bash -lc "node -v"
  register: checknodejsver
  become_user: "{{ deploy_user }}"
  become: yes
- debug: var=checknodejsver.stdout_lines

- name: NPM-PPA > Check npm version
  shell: bash -lc "npm -v"
  register: checknpmver
  become_user: "{{ deploy_user }}"
  become: yes
- debug: var=checknpmver.stdout_lines
