# Get SSH Private & Public key for Deploy user
#1. Config SSH Private & Public key for Deploy user
- name: DISTRIBUTE-KEY > Copy {{ deploy_user }} private key to Bastion
  template:
    src: .{{ deploy_user }}-keypair-{{ env }}.j2
    dest: /home/{{ deploy_user }}/.ssh/{{ deploy_user }}
    owner: "{{ deploy_user }}"
    group: "{{ deploy_user }}"
    mode: 0400
  become: true
  become_user: '{{ deploy_user }}'
  when: type=="bastion"

#2. Copy Public key for Deploy user
- name: DISTRIBUTE-KEY > Copy {{ deploy_user }} public key to {{ env }}
  template:
    src: .{{ deploy_user }}-keypair-{{ env }}.pub.j2
    dest: /home/{{ deploy_user }}/.ssh/authorized_keys
    owner: "{{ deploy_user }}"
    group: "{{ deploy_user }}"
    mode: 0600
  when: env=="stg" or env=="prod" or env=="dev"
  become_user: '{{ deploy_user }}'
  become: yes

# Config SSH Key *.pem for {{ ansible_ssh_user }} user to Bastion
- name: DISTRIBUTE-KEY > Copy private key for {{ ansible_ssh_user }}
  template:
    src: .{{ project }}-keypair-{{ env }}.pem.j2
    dest: /home/{{ ansible_ssh_user }}/.ssh/{{ project }}-keypair-{{ env }}.pem
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"
    mode: 0400
  become: true
  become_user: '{{ ansible_ssh_user }}'
  when: type=="bastion"

# Git deploy-key for Backend (api, admin, worker)
#1. Copy deploy-key for Backend (api, admin, worker)
- name: DISTRIBUTE-KEY > Copy deploy-key for Backend
  template:
    src: .{{ project }}-git-deploy-key-backend.j2
    dest: /home/{{ deploy_user }}/.ssh/{{ project }}-git-deploy-key-backend
    owner: "{{ deploy_user }}"
    group: "{{ deploy_user }}"
    mode: 0400
  when: type=="api" or type=="admin" or type=="batch" or type=="worker"
  become_user: '{{ deploy_user }}'
  become: yes

#2 Copy ssh-config for Backend (api, admin, worker)
- name: DISTRIBUTE-KEY > Copy ssh_config for Backend
  template:
    src: ssh-config-backend.j2
    dest: ~/.ssh/config
    owner: "{{ deploy_user }}"
    group: "{{ deploy_user }}"
    mode: 0600
  when: type=="api" or type=="admin" or type=="batch" or type=="worker"
  become_user: '{{ deploy_user }}'
  become: yes

# Git deploy-key for Cons
#1. Copy deploy-key for Cons
- name: DISTRIBUTE-KEY > Copy deploy-key for Cons
  template:
    src: .{{ project }}-git-deploy-key-cons.j2
    dest: /home/{{ deploy_user }}/.ssh/cons-git-deploy-key
    owner: "{{ deploy_user }}"
    group: "{{ deploy_user }}"
    mode: 0400
  when: type=="cons"
  become_user: '{{ deploy_user }}'
  become: yes

#2 Copy ssh-config for Cons
- name: DISTRIBUTE-KEY > Copy ssh_config for Cons
  template:
    src: ssh-config-cons.j2
    dest: ~/.ssh/config
    owner: "{{ deploy_user }}"
    group: "{{ deploy_user }}"
    mode: 0600
  when: type=="cons"
  become_user: '{{ deploy_user }}'
  become: yes
