# Install libmysql-java
- name: JMETER-INSTALL > Install libmysql-java
  apt:
    name: libmysql-java
    update-cache: yes

# Copy libmysql-java to jmeter classpath
- name: JMETER-INSTALL > Add libmysql-java to classpath
  command: "cp /usr/share/java/mysql-connector-java.jar {{ jmeter_prefix }}/jmeter/lib/"
